<?php
class M4c695df4aba043babe0d0fdcb36fd16a extends CakeMigration {

/**
 * Migration description
 *
 * @var string
 * @access public
 */
	public $description = '';

/**
 * Actions to be performed
 *
 * @var array $migration
 * @access public
 */
	public $migration = array(
		'up' => array(
			'create_table' => array(
				'acos' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'parent_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'model' => array('type' => 'string', 'null' => true, 'default' => NULL),
					'foreign_key' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10, 'key' => 'index'),
					'alias' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index'),
					'lft' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10, 'key' => 'index'),
					'rght' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'ACOS_LFT_RGHT' => array('column' => array('lft', 'rght'), 'unique' => 0),
						'ACOS_ALIAS' => array('column' => 'alias', 'unique' => 0),
						'ACOS_MODEL_FOREIGN_KEY' => array('column' => array('foreign_key', 'model'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'InnoDB'),
				),
				'addresses' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'address_line_1' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'address_line_2' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'city' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'state' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 2),
					'zip' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 5),
					'lat' => array('type' => 'float', 'null' => true, 'default' => NULL, 'length' => '10,7'),
					'lng' => array('type' => 'float', 'null' => true, 'default' => NULL, 'length' => '10,7'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'foreign_key' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'model' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'primary' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
					'active' => array('type' => 'boolean', 'null' => true, 'default' => '1'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'alerts' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 45),
					'description' => array('type' => 'text', 'null' => false, 'default' => NULL),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'group_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10),
					'importance' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 12),
					'expires' => array('type' => 'date', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'alerts_users' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'alert_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'answers' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'roster_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'question_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'description' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'api_classes' => array(
					'id' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 36, 'key' => 'primary'),
					'api_package_id' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 36, 'key' => 'index'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 200),
					'slug' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 200),
					'file_name' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'method_index' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'property_index' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'flags' => array('type' => 'integer', 'null' => true, 'default' => '0', 'length' => 5),
					'coverage_cache' => array('type' => 'float', 'null' => true, 'default' => NULL, 'length' => '4,4'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'api_package_id' => array('column' => 'api_package_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'api_packages' => array(
					'id' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 36, 'key' => 'primary'),
					'parent_id' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 36, 'key' => 'index'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL),
					'slug' => array('type' => 'string', 'null' => false, 'default' => NULL),
					'lft' => array('type' => 'integer', 'null' => true, 'default' => NULL),
					'rght' => array('type' => 'integer', 'null' => true, 'default' => NULL),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'parent_id' => array('column' => 'parent_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'app_settings' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 45),
					'description' => array('type' => 'string', 'null' => false, 'default' => NULL),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'value' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'model' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45),
					'html' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'aros' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'parent_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'model' => array('type' => 'string', 'null' => true, 'default' => NULL),
					'foreign_key' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10, 'key' => 'index'),
					'alias' => array('type' => 'string', 'null' => true, 'default' => NULL),
					'lft' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'rght' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10, 'key' => 'index'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'AROS_LFT_RGHT' => array('column' => array('rght', 'lft'), 'unique' => 0),
						'AROS_MODEL_FOREIGN_KEY' => array('column' => array('foreign_key', 'model'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'InnoDB'),
				),
				'aros_acos' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'aro_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'index'),
					'aco_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10),
					'_create' => array('type' => 'string', 'null' => false, 'default' => '0', 'length' => 2),
					'_read' => array('type' => 'string', 'null' => false, 'default' => '0', 'length' => 2),
					'_update' => array('type' => 'string', 'null' => false, 'default' => '0', 'length' => 2),
					'_delete' => array('type' => 'string', 'null' => false, 'default' => '0', 'length' => 2),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'ARO_ACO_KEY' => array('column' => array('aro_id', 'aco_id'), 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'InnoDB'),
				),
				'attachments' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'model' => array('type' => 'string', 'null' => false, 'default' => NULL),
					'foreign_key' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 45),
					'dirname' => array('type' => 'string', 'null' => true, 'default' => NULL),
					'basename' => array('type' => 'string', 'null' => false, 'default' => NULL),
					'checksum' => array('type' => 'string', 'null' => false, 'default' => NULL),
					'alternative' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 50),
					'group' => array('type' => 'string', 'null' => true, 'default' => NULL),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'campuses' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 64),
					'description' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'active' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'campuses_revs' => array(
					'version_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'version_created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 64),
					'description' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'active' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'version_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'classifications' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'comment_types' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 45),
					'group_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'comments' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'comment_type_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'comment' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'created_by' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'dates' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'start_date' => array('type' => 'date', 'null' => true, 'default' => NULL),
					'end_date' => array('type' => 'date', 'null' => true, 'default' => NULL),
					'start_time' => array('type' => 'time', 'null' => true, 'default' => NULL),
					'end_time' => array('type' => 'time', 'null' => true, 'default' => NULL),
					'all_day' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
					'permanent' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
					'recurring' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
					'recurrance_type' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 10),
					'frequency' => array('type' => 'integer', 'null' => true, 'default' => '0', 'length' => 2),
					'weekday' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 2),
					'day' => array('type' => 'integer', 'null' => true, 'default' => '0', 'length' => 2),
					'involvement_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'exemption' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
					'offset' => array('type' => 'integer', 'null' => true, 'default' => '0', 'length' => 2),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'errors' => array(
					'id' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 36, 'key' => 'primary'),
					'level' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 15),
					'file' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 200),
					'line' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 5),
					'message' => array('type' => 'text', 'null' => false, 'default' => NULL),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'groups' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45),
					'conditional' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 1),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'parent_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'lft' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10),
					'rght' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'household_members' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'household_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'user_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'confirmed' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'households' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'contact_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'involvement_types' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'description' => array('type' => 'text', 'null' => false, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'involvements' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'ministry_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'involvement_type_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 64),
					'description' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'roster_limit' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 3),
					'roster_visible' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
					'group_id' => array('type' => 'integer', 'null' => true, 'default' => '0', 'length' => 10),
					'signup' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
					'take_payment' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
					'offer_childcare' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
					'active' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'force_payment' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'involvements_revs' => array(
					'version_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'version_created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'ministry_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'involvement_type_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 64),
					'description' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'roster_limit' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 3),
					'roster_visible' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
					'group_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'signup' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
					'require_payment' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
					'offer_childcare' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
					'active' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'version_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'job_categories' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'leaders' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'model' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'model_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'logs' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'title' => array('type' => 'string', 'null' => true, 'default' => NULL),
					'description' => array('type' => 'string', 'null' => true, 'default' => NULL),
					'model' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'model_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'action' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'user_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'merge_requests' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'model' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 45),
					'model_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10),
					'merge_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10),
					'requester_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'ministries' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 64),
					'description' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'parent_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'lft' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'rght' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'campus_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'group_id' => array('type' => 'integer', 'null' => true, 'default' => '9', 'length' => 10),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'active' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'ministries_revs' => array(
					'version_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'version_created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 64),
					'description' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'campus_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'group_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'active' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
					'parent_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'indexes' => array(
						'PRIMARY' => array('column' => 'version_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'notifications' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'read' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
					'type' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 45),
					'body' => array('type' => 'text', 'null' => false, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'payment_options' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'involvement_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 64),
					'total' => array('type' => 'float', 'null' => true, 'default' => NULL, 'length' => 10),
					'deposit' => array('type' => 'float', 'null' => true, 'default' => NULL, 'length' => 10),
					'childcare' => array('type' => 'float', 'null' => true, 'default' => NULL, 'length' => 10),
					'account_code' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'tax_deductible' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'payment_types' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 45),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'payments' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'roster_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'amount' => array('type' => 'float', 'null' => true, 'default' => NULL, 'length' => 10),
					'payment_type_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'number' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 20),
					'transaction_id' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 64),
					'payment_placed_by' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'refunded' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
					'payment_option_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'comment' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'profiles' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'first_name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'last_name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'gender' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 1),
					'birth_date' => array('type' => 'date', 'null' => true, 'default' => NULL),
					'adult' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
					'classification_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'marital_status' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 1),
					'job_category_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'occupation' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 64),
					'accepted_christ' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
					'accepted_christ_year' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 4),
					'baptism_date' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'allergies' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'special_needs' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'special_alert' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'cell_phone' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 10),
					'home_phone' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 10),
					'work_phone' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 10),
					'primary_email' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 64),
					'alternate_email_1' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 64),
					'alternate_email_2' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 64),
					'cpr_certified_date' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'baby_dedication_date' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'qualified_leader' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
					'background_check_complete' => array('type' => 'boolean', 'null' => true, 'default' => NULL),
					'background_check_by' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'background_check_date' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'grade' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 1),
					'graduation_year' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 4),
					'created_by' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'created_by_type' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'default_address' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'campus_id' => array('type' => 'integer', 'null' => true, 'default' => '0', 'length' => 10),
					'email_on_notification' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'allow_sponsorage' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'household_contact_signups' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'elementary_school_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'middle_school_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'high_school_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'college_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'publications' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 64),
					'link' => array('type' => 'string', 'null' => true, 'default' => NULL),
					'description' => array('type' => 'string', 'null' => true, 'default' => NULL),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'publications_users' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'publication_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'user_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'questions' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'involvement_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'order' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 2),
					'description' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'regions' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 45),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'InnoDB'),
				),
				'roles' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'ministry_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45),
					'description' => array('type' => 'text', 'null' => true, 'default' => NULL),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'rosters' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10),
					'involvement_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10),
					'role_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'payment_option_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'parent_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10),
					'roster_status' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'schools' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 64),
					'type' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 10),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'users' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'username' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32),
					'password' => array('type' => 'string', 'null' => true, 'default' => NULL),
					'active' => array('type' => 'boolean', 'null' => true, 'default' => '1'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'last_logged_in' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'flagged' => array('type' => 'boolean', 'null' => false, 'default' => NULL),
					'group_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'zipcodes' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'region_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10),
					'zip' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 5),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'InnoDB'),
				),
			),
		),
		'down' => array(
			'drop_table' => array(
				'acos', 'addresses', 'alerts', 'alerts_users', 'answers', 'api_classes', 'api_packages', 'app_settings', 'aros', 'aros_acos', 'attachments', 'campuses', 'campuses_revs', 'classifications', 'comment_types', 'comments', 'dates', 'errors', 'groups', 'household_members', 'households', 'involvement_types', 'involvements', 'involvements_revs', 'job_categories', 'leaders', 'logs', 'merge_requests', 'ministries', 'ministries_revs', 'notifications', 'payment_options', 'payment_types', 'payments', 'profiles', 'publications', 'publications_users', 'questions', 'regions', 'roles', 'rosters', 'schools', 'users', 'zipcodes'
			),
		),
	);

/**
 * Before migration callback
 *
 * @param string $direction, up or down direction of migration process
 * @return boolean Should process continue
 * @access public
 */
	public function before($direction) {
		return true;
	}

/**
 * After migration callback
 *
 * @param string $direction, up or down direction of migration process
 * @return boolean Should process continue
 * @access public
 */
	public function after($direction) {
		return true;
	}
}
?>